# Generated by Django 5.0.1 on 2024-01-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagal', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
