# Generated by Django 5.0.1 on 2024-01-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagal', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
